/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;
\c vet_clinic;

CREATE TABLE animals(
id INT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(50) NOT NULL,
date_of_birth date,
escape_attempts INT,
neutered boolean,
weight_kg decimal(4,2));

ALTER TABLE animals ADD COLUMN species varchar(50);